Followers, allies, clans
codewars/docs pull request #217
Opened 2020-12-31 01:21 UTC by hobovsky

Discussion: #201 
Deploy preview: [here]()

2020-12-31 04:35 UTC, DonaldKellett approved these changes

2021-01-01 15:02 UTC, Steffan153 requested changes

2021-01-01 15:02 UTC, Steffan153 commented on content/concepts/clans-allies-and-followers/followers.md
> +On your profile page, you can find `Social` tab, which contains a couple of leaderboards. One of them, titled **"Following"**, contains a list and honor ranking of all users followed by you. Another
```suggestion
On your profile page, you can find the `Social` tab, which contains a couple of leaderboards. One of them, titled **"Following"**, contains a list and honor ranking of all users followed by you. Another one, titled **"Followers"**, provides a similar list of your followers.
```

2021-01-01 15:02 UTC, Steffan153 commented on content/concepts/clans-allies-and-followers/followers.md
> +When viewing the solutions of a kata, you can choose to see only these from users you are following. This is a great way to easily find solutions from warriors you respect or know personally.
```suggestion
When viewing the solutions of a kata, you can choose to see only those from users you are following. This is a great way to easily find solutions from warriors you respect or know personally.
```

2021-01-01 15:31 UTC, Steffan153 approved these changes

2021-01-02 23:32 UTC, kazk approved these changes

2021-01-03 04:09 UTC, hobovsky commented
I wanted this one to wait for wording review from @DonaldKellett, but since kazk greenlighted it, I am going to merge this.

2021-01-03 04:09 UTC, merged

2021-01-03 04:27 UTC, kazk commented
FYI, I focus on checking misinformation and not spelling/grammar. I was relying on @DonaldKellett for those as well :laughing: I didn't notice anything obvious, and we can always fix it later.