Note on input validation and other distractions
codewars/docs pull request #267
Opened 2021-02-18 15:34 UTC by hobovsky

2021-02-19 06:18 UTC, kazk approved these changes

2021-02-20 02:06 UTC, DonaldKellett requested changes

2021-02-20 02:06 UTC, DonaldKellett commented on content/authoring/guidelines/kata.md
>  - **Make requirements very clear.** If kata is not a puzzle, describe everything that will be tested and leave no surprises. The reason for every failing test case should be evidently visible in the
```suggestion
- **Make requirements very clear.** If the kata is not a puzzle, describe everything that will be tested and leave no surprises. The reason for every failing test case should be evidently visible in the description of the kata.
```

2021-02-26 17:33 UTC, Steffan153 approved these changes

2021-02-26 18:14 UTC, merged