Update RISC-V ISA documentation
codewars/docs pull request #492
Opened 2023-12-27 02:49 UTC by StarsDown64

Simple edit to reflect the extra extensions supported in codewars/riscv#7.
Still not completely happy with line 13, I feel like it's not visually appealing but the ISA string the closest there is to a version number. Maybe listing the QEMU version? Not sure.
As I will comment in codewars/riscv#7 as well, Zbkx is not necessary as it's in both Zk and Zks shorthands.

2023-12-27 02:51 UTC, StarsDown64 commented
@dramforever request your thoughts.

2023-12-27 03:48 UTC, dramforever commented
LGTM. I think for version string maybe QEMU as you said and also GCC and Binutils version?

2023-12-27 04:41 UTC, StarsDown64 commented
Now that I think about it, none of the QEMU, GCC, or any runner tool version is specific to riscv language, so I wouldn't think it appropriate for the riscv specific docs.

2023-12-27 05:34 UTC, dramforever commented
My understanding is that GCC, Binutils, QEMU *are* in fact unique to `riscv` language. Presently at least, no other language uses QEMU for emulation, and the GCC and Binutils here are cross compilation toolchains, which also no other language uses.

2023-12-27 05:46 UTC, StarsDown64 commented
Huh. I see. If you know where to look, could you get me any relevant version info to include? I'm not familiar at all with the runner or toolchain.

2023-12-27 06:54 UTC, dramforever commented
Just had an idea to "cheat" and do a `system("gcc --version"); system("as --version");` in a kumite and got 

```
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
GNU assembler (GNU Binutils for Ubuntu) 2.38
```

As for QEMU I think this means we're using 7.1 https://github.com/codewars/riscv/pull/9

2023-12-27 12:25 UTC, DonaldKellett approved these changes
Very detailed, LGTM!

2023-12-27 12:31 UTC, hobovsky commented
Looking at the preview here: https://deploy-preview-492--reverent-edison-2864ea.netlify.app/languages/riscv I am not sure I like the style of the asterisk/dagger/etc. annotations. Formatting is a bit off, and I htink they might look somewhat unusual to people more familiar with just numbered annotations like <sup>1)</sup> . What do you think?

2023-12-27 12:39 UTC, DonaldKellett commented
The style seems in line with official RISC-V documentation, but I agree their appearance isn't that common in the Codewars docs and might not fit in well with the rest of the documentation.

I'm personally not bothered by it but let's collect some opinions from a few others before we decide whether to stick to the current style or revert to plain numbered annotations.

2023-12-27 16:56 UTC, StarsDown64 commented
Is there precedent elsewhere in the docs? I searched through the repo and found one other instance of the single dagger (in content\gamification\priveleges.md:27,32) and none of the double dagger or section symbol. I tried looking for `\d\)` or `\[\d\]` but couldn't find any being used as footnote markers.

2023-12-27 17:38 UTC, hobovsky commented
Numbers vs daggers is one thing, and we can fix it later if needed. But another thing which puts me off a bit is that the footnote markers seem to be not superscripted,  neither in the main text, nor in footnotes themselves?

2023-12-27 18:29 UTC, StarsDown64 commented
I see what you mean. I like the look of superscripts as well. Adding.

2023-12-31 14:18 UTC, DonaldKellett approved these changes

2023-12-31 14:53 UTC, error256 requested changes

2023-12-31 14:53 UTC, error256 commented on content/languages/riscv/index.md
> +- <sup>*</sup>[RISC-V Unprivileged Specification](https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-056b6ff-2023-10-02/unpriv-isa-asciidoc.pdf)
These aren't recognized as markdown links: https://deploy-preview-492--reverent-edison-2864ea.netlify.app/languages/riscv/

2024-01-03 01:16 UTC, StarsDown64 commented on content/languages/riscv/index.md
> +- <sup>*</sup>[RISC-V Unprivileged Specification](https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-056b6ff-2023-10-02/unpriv-isa-asciidoc.pdf)
Fixed

2024-01-03 08:41 UTC, error256 approved these changes

2024-01-03 14:03 UTC, merged